### ISSUE TITLE
这个的触发条件是什么，我看已经有报错，但是没有推送，但是测试推送是可以的

### ISSUE THREAD

**Issue by leochen-g** [xiaomao361/sddp#1]

**Comment by xiaomao361** [comment]
就是说，你添加插件以后测试，钉钉可以收到，但是实际报bug的时候 钉钉没有收到是么？
那可能是，在左侧栏 警报里面 你需要添加新的 报警的规则，然后 规则里面 有配置报警的方式。里面选择 send a notification via "dingtalk"

**Comment by xiaomao361** [comment]
> _No description provided._

就是说，你添加插件以后测试，钉钉可以收到，但是实际报bug的时候 钉钉没有收到是么？
那可能是，在左侧栏 警报里面 你需要添加新的 报警的规则，然后 规则里面 有配置报警的方式。里面选择 send a notification via "dingtalk"
