### ISSUE TITLE
大佬安装不上

### ISSUE THREAD

**Issue by xdkaka** [xiaomao361/sddp#2]
worker_1                                    | Installing additional dependencies...
worker_1                                    | ERROR: Invalid requirement: 'sddp=0.2.6' (from line 1 of /etc/sentry/requirements.txt)
worker_1                                    | Hint: = is not a valid operator. Did you mean == ?
worker_1                                    | Installing additional dependencies...
worker_1                                    | ERROR: Invalid requirement: 'sddp=0.2.6' (from line 1 of /etc/sentry/requirements.txt)
worker_1                                    | Hint: = is not a valid operator. Did you mean == ?

**Comment by xiaomao361** [comment]
哈哈，我好像是少写了个=号 ，那个文件里面需要写'sddp==0.2.6' 我去改下哈。没注意
